-- no-transaction
-- find_pending's cursor is now an exact (created_at, id) keyset (cycle 351,
-- closes the pagination data-loss bug a timestamp-only cursor risked once
-- results were paginated). ORDER BY created_at ASC, id ASC needs `id` in the
-- index to avoid an extra in-memory sort on every poll (every device polls
-- every ~3s) once a device has more matching rows than fit the index's
-- leading columns can return pre-sorted. Replaces 0001's two-column index
-- with a three-column one covering the full sort/cursor key.
--
-- CREATE INDEX CONCURRENTLY cannot run inside sqlx's default migration
-- transaction (Postgres forbids CONCURRENTLY in a transaction block at
-- all — it isn't just slower, it's a hard error), hence `-- no-transaction`
-- above. Split into its own create-first migration (0012 drops the old
-- index) so the table has BOTH indexes usable throughout, and the build
-- itself doesn't hold envelopes' ACCESS EXCLUSIVE lock for the ~3s poll
-- loop's duration — security-auditor cycle 352 flagged the original single
-- DROP-then-CREATE-in-transaction migration as a full messaging outage for
-- the whole index build.
-- OPERATIONAL NOTE (security-auditor cycle 353): if this CREATE is interrupted
-- (deploy cancelled, connection dropped, deadlock) Postgres leaves an INVALID
-- index under this name. `IF NOT EXISTS` then no-ops on retry without
-- rebuilding it, and the query planner permanently ignores an invalid index —
-- the next migration would then drop the only good (two-column) index,
-- leaving every poll to seq-scan `envelopes`. Automated (cycle 358): 0012
-- guards against exactly this — a transactional `DO` block that aborts the
-- whole migration run if `pg_index.indisvalid` is false for this index,
-- before 0013's `DROP INDEX CONCURRENTLY` of the fallback index can run.
CREATE INDEX CONCURRENTLY IF NOT EXISTS envelopes_recipient_created_id_idx
    ON envelopes(recipient_device_id, created_at, id);
