apiVersion: v1
kind: Service
metadata:
  name: {{ include "powehi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "powehi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "powehi.selectorLabels" . | nindent 4 }}
  ports:
    - name: public
      port: {{ .Values.service.publicPort }}
      targetPort: public
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      protocol: TCP
