apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "powehi.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "powehi.labels" . | nindent 4 }}
automountServiceAccountToken: false
