[package]
name = "powehi-proto"
description = "Protobuf definitions for the Powehi inter-region gRPC mesh."
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }

[build-dependencies]
tonic-build = "0.12"
protox = "0.7"
