//! Web Push subscription (RFC 8291 / RFC 8292).
//!
//! Stores the browser-supplied push endpoint and ECDH key material. These keys
//! are *public* material generated by the browser's PushManager — they are not
//! server secrets. The server uses them only to address an empty wake-up push;
//! the notification body is always empty (zero-knowledge: no content travels
//! through the push service). See prd.md push-notification section.
//!
//! Security invariant: `endpoint`, `p256dh`, and `auth_secret` are
//! device-identifiable and MUST NEVER be logged (rule: no-plaintext-logging).

use crate::device::DeviceId;

#[derive(Debug, Clone)]
pub struct PushSubscription {
    pub device_id: DeviceId,
    /// HTTPS URL of the push service endpoint.
    pub endpoint: String,
    /// Browser's P-256 public key (uncompressed, 65 bytes), ECDH key for ECE.
    pub p256dh: Vec<u8>,
    /// 16-byte random auth secret from the browser.
    pub auth_secret: Vec<u8>,
}

impl PushSubscription {
    pub fn new(
        device_id: DeviceId,
        endpoint: String,
        p256dh: Vec<u8>,
        auth_secret: Vec<u8>,
    ) -> Self {
        Self {
            device_id,
            endpoint,
            p256dh,
            auth_secret,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn push_subscription_holds_fields() {
        let device_id = DeviceId::new();
        let sub = PushSubscription::new(
            device_id.clone(),
            "https://push.example/abc".into(),
            vec![4u8; 65],
            vec![0u8; 16],
        );
        assert_eq!(sub.device_id, device_id);
        assert_eq!(sub.endpoint, "https://push.example/abc");
        assert_eq!(sub.p256dh.len(), 65);
        assert_eq!(sub.auth_secret.len(), 16);
    }
}
